config/routes.rb
Boaz::Application.routes.draw do
  resources :clients, :orders, :restorations

  root to: 'clients#index'
end

app/models/client.rb
class Client < ActiveRecord::Base
	validates :first_name, :presence => true 
	validates :last_name, :presence => true 
	validates :email, :presence => true

	has_many :orders
	has_many :restorations

end

app/models/order.rb
class Order < ActiveRecord::Base
	

	belongs_to :client
end

app/models/restoration.rb
class Restoration < ActiveRecord::Base
	validates :instrument, :presence => true 
	validates :description, :presence => true 
	validates :price_offer, :presence => true
	
	belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	def index
		@clients = Client.all
	end

	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)
		
		if @client.save
			redirect_to @client
		else
			render 'new'
		end
	end

	def show
		@client = Client.find(params[:id])
	end

	def edit
	end

	def destroy
	end

	private
	def client_params
		params.require(:client).permit(:first_name, :last_name, :email, :cell_phone, :home_phone, :mailing_add, :billing_add)
	end
end

app/controllers/restorations_controller.rb
class RestorationsController < ApplicationController
  def index
    @restorations = Restoration.all
  end

  def new
    @restoration = Restoration.new
  end

  def create
    @restoration = Restoration.new(restoration_params)
    
    if @restoration.save
        redirect_to @restoration
    else
      render 'new'
    end
  end

  def show
    @restoration = Restoration.find(params[:id])
  end

  def edit
  end

  def destroy
  end

  private
  def restoration_params
    params.require(:restoration).permit(:instrument, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/restoration_helper.rb
module RestorationHelper
end

app/views/clients/index.html.erb
<h1> Client List </h1>

<table>
  <tr>
    <th>First</th>
    <th>Last</th>
    <th>Email</th>
    <th>Cell Number</th>
    <th>Home Number</th>
    <th>Mailing Address</th>
    <th>Billing Address</th>
    <th>New Orders</th>
    <th>Restorations</th>
    <th>All Orders</th>
  </tr>

  <% @clients.each do |client| %>
    <tr>
      <td><%= client.first_name %></td>
      <td><%= client.last_name %></td>
      <td><%= client.email %></td>
      <td><%= client.cell_phone %></td>
      <td><%= client.home_phone %></td>
      <td><%= client.mailing_add %></td>
      <td><%= client.billing_add %></td>
      <td><%= link_to 'View', restorations_path %></td>
      <td><%= link_to 'View', restorations_path %></td>
      <td><%= link_to 'Show All', client_path(client.id) %></td>
    </tr>
  <% end %>

</table>
<%= link_to 'Add Client', new_client_path %>

app/views/clients/new.html.erb
<h1> New Client </h1>

<%= form_for :client, url: clients_path do |f| %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

   <p>
    <%= f.label :cell_phone %><br>
    <%= f.text_field :cell_phone %>
  </p>

   <p>
    <%= f.label :home_phone %><br>
    <%= f.text_field :home_phone %>
  </p>

   <p>
    <%= f.label "Mailing Address" %><br>
    <%= f.text_field :mailing_add %>
  </p>

   <p>
    <%= f.label "Billing Address" %><br>
    <%= f.text_field :billing_add %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Order Restoration', new_restoration_path %>
<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<h1> <%= "#{@client.first_name} #{@client.last_name}" %> </h1>

<%= link_to 'Restoration Order', new_restoration_path %>
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Client Database</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restorations/index.html.erb
<h1>Restoration Work</h1>

<table>
  <tr>
    <th>Instrument</th>
    <th>Description</th>
    <th>Price Offer</th>
    <th>Client</th>
  </tr>

  <% @restorations.each do |restoration| %>
    <tr>
      <td><%= restoration.instrument %></td>
      <td><%= restoration.description %></td>
      <td><%= restoration.price_offer %></td>
 	  <td><%= "#{@client.first_name} #{@client.last_name}" %></td>
    </tr>
  <% end %>

</table>
<%= link_to 'Back', clients_path %>

app/views/restorations/new.html.erb
<h1>Restoration Order</h1>

<%= form_for :restoration, url: restorations_path do |f| %>
  <p>
    <%= f.label :instrument %><br>
    <%= f.text_field :instrument %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

   <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', clients_path %>

app/views/restorations/show.html.erb
<h1>Restoration#show</h1>
<p>Find me in app/views/restoration/show.html.erb</p>